services:
  ollama:
    container_name: ollama
    volumes:
      - ./backend/data/ollama:/root/.ollama
      - ../models/:/custom/models
    environment:
      - OLLAMA_MODELS=/custom/models
      - OLLAMA_SERVER_HOST=0.0.0.0
    ports:
      - "11434:21434"
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    # image: ollama/ollama:0.5.8
    networks:
      - training 

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ./frontend/data/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:28080
    env_file:
      - .env
      # - 'OLLAMA_BASE_URL='
      # - 'WEBUI_SECRET_KEY='
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - training 
    

  qdrant:
    # image: qdrant/qdrant
    image: qdrant/qdrant:v1.15
    container_name: qdrant
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"   
    restart: unless-stopped
    networks:
      - training 

networks:
  training:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
  qdrant_data: {}